- name: Cloning roles repository.
  hosts: all
  connection: local
  become: true

  vars:
    git_repository:
    git_branch:

  tasks:
  - name: Create roles directory.
    file:
      path: /etc/ansible/roles
      state: directory
      mode: '0755'
  
  - name: Checkout roles repository.
    ansible.builtin.git:
      repo: "{{ git_repository }}"
      dest: /etc/ansible/roles
      version: "{{ git_branch }}"
